services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce_web_coverage
        stop_grace_period: 30s
        init: true
        ports:
            - "90:80"
        depends_on:
            - nopcommerce_mysql_server
        volumes:
            - ./coverage:/coverage

    nopcommerce_mysql_server:
        image: "mysql:8.1.0"
        container_name: nopcommerce_mysql_server_coverage
        command: "--default-authentication-plugin=mysql_native_password"
        restart: "always"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "nopCommerce_db_password"
        volumes:
            - mysql_db:/var/lib/mysql

volumes:
  nopcommerce_data:
  mysql_db: